### ISSUE TITLE
CMP demo tasks list tracking

### ISSUE THREAD

**Issue by minhhn2910** [sbip-sg/interchain-accounts-demo#4]
- [ ] Oracle service for on host chain, simulating the simplified chainlink node's model: listening to cmp events -> process -> submit tx callback  https://github.com/sbip-sg/interchain-accounts-demo/commit/b86d1cd667d587e1c5d01b37587e5cb8c71404d2
- [ ] Use name service as the POC application, each name domain simulates a product categories (e.g. ".com", ".org") https://github.com/sbip-sg/interchain-accounts-demo/commit/b86d1cd667d587e1c5d01b37587e5cb8c71404d2
- [ ] Basic workflow for testing cmp on hostchain: banned list + price range for each product type https://github.com/sbip-sg/interchain-accounts-demo/commit/b86d1cd667d587e1c5d01b37587e5cb8c71404d2
- [ ] Oracle on controller chain TBD 
- [ ] Implement actual bank transfer for name service module when tx is settled.
- [ ] Detach host verification logic  into a separate module 
- [ ] TBD extra items

**Comment by minhhn2910** [comment]
Completed in https://github.com/sbip-sg/interchain-accounts-demo/pull/7 . The remaining tasks if exist should be:  Documentation, experiment setup, fix small bugs + small changes in workflow.
